services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXPORTER_PASSWORD=${POSTGRES_EXPORTER_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default  
  
  redis:
    image: redis:7.4.2
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default  

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_BROWSER=on
    ports:
      - "9000:9000" 
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 2s
      retries: 5
    networks:
      - default
  
  minio-init:
    image: minio/mc:RELEASE.2025-04-08T15-39-49Z
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    volumes:
      - ./minio-init.sh:/minio-init.sh
    entrypoint: ["/bin/sh", "-c", "chmod +x /minio-init.sh && /minio-init.sh"]
    networks:
      - default

  mailpit:
    image: axllent/mailpit:v1.24
    container_name: mailpit
    ports:
      - "8025:8025"  
      - "1025:1025"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data: